### PR TITLE
Docs/metadata project docs

### LINKED ISSUE #149: Documentation should reflect all components and the workflow
#### Description

We need to update documentation to reflect all components and the workflow

#### DoD (Definition of Done)

Updated documentation

#### Testing

Peer review

### PR DESCRIPTION
**Pull request by blankdots**
### Related issues

Fixes #149 

### Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] updated Docs

### Changes Made

1. updated documentation
2. revisited some env variables to make more sense
3. fixes for typos

### Testing

- [x] Tests do not apply

### Mentions

View docs rendered here: https://metadata-submitter.readthedocs.io/en/docs-metadata-project-docs/

Also merged here PR #166 as it was based on this

### CODE REVIEW

**Review by csc-jm — APPROVED** [review]
All looks good. Merry Xmas!

**Comment by hannyle** [comment]
Looks good and clear to me.
One thing we may add in `Frontend - Styles` is Material UI Customized theme for CSC is set in `theme.js`, and added to `index.js` for use

**Review by hannyle — APPROVED** [review]

**Comment by blankdots** [comment]
> One thing we may add in `Frontend - Styles` is Material UI Customized theme for CSC is set in `theme.js`, and added to `index.js` for use

good point will add that

**Comment by blankdots** [comment]
2 approvals received so will merge to move things forward, any additions/changes can be tackled in follow-up PRs

**Pull request merged**
