### PR TITLE
Refactor/aiohttp session

### PR DESCRIPTION
**Pull request by genie9**
### Related issues

Introduce aiohttp_session as a way to handle the session instead of the custom way that was there before.

### Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### Changes Made

1. added `aiohttp_session` as dependency
2. fixed function comments and missing information
3. refactored auth to include  new session management 
4. refactored unit tests
5. fixed some typing `Any`
6. migrated to variables used by motor 3 for SSL https://motor.readthedocs.io/en/stable/migrate-to-motor-3.html?highlight=ssl_certfile#renamed-uri-options

### Testing

- [x] Unit Tests

### CODE REVIEW

**Comment by hannyle** [comment]
I tested this branch and e2e test still fail from github CI pipeline.

**Comment by csc-felipe** [comment]
@hannyle, does it also fail if you run locally?

**Comment by hannyle** [comment]
> @hannyle, does it also fail if you run locally?

They run fine locally.

**Comment by genie9** [comment]
@hannyle is it the same redirect issue?

**Comment by hannyle** [comment]
> @hannyle is it the same redirect issue?

Yes, the issue of redirection from `localhost:5430` --> `localhost:5430/error401`

**Comment by csc-felipe** [comment]
We have changed so much code after this was initially made! I will try to make it work again, and see if the previous issues will still exist.

**Comment by csc-felipe** [comment]
It seems to run as expected ^^. Still need to investigate the previously existing issues.

**Comment by csc-felipe** [comment]
The issue seems to come from changing the setup for checking for valid sessions in `middlewares.py`. There used to be a check for static files, which was removed. Restoring that removes the unexpected redirect.

It's still a bit of an issue, though. Because the previous code was checking for static routes, which the new one discarded that. But at the same time, we don't know all the static routes that exist, so we can't check them. We should instead serve static files only with external hosting, or change the setup.

We don't really test static routes in the backend, but the frontend does.

Checking sessions was done on a global level, but it shouldn't check routes that match the static routes that would match the frontend. Those should always return the static files.

It would be nice to be able to mark (decorate) routes that are checked, instead of a global check which should keep track of which routes exist. Sounds like a prone to error approach.

Perhaps we should use nested applications, so we can apply the session checking middleware only to the API routes, and the public routes are not checked. We might need then to prepend the API routes with, for e.g. `/api`. I think this would be a good solution.

**Comment by csc-felipe** [comment]
This PR was already quite large, so I'll make another PR, which makes some changes to API, and fixes the issues created by this one, mentioned above.

**Review by teemukataja — APPROVED** [review]
with https://github.com/CSCfi/metadata-submitter/pull/476

**Pull request merged**
