### PR TITLE
add lastModified to folders

### LINKED ISSUE #363: add last modified to folder to enable filtering in front-end
#### Description

We need to track when a folder was last modified, we probably need to track when an object in the folder was last updated
We should add a similar format to `dateCreated`

#### DoD (Definition of Done)

`lastModified` is available for filtering via API by front-end

#### Testing

Unit/Integration tests

### PR DESCRIPTION
**Pull request by blankdots**
### Description

we add last modified when we create the folder and it is the same value as date created

We replace this value on:
- object create, update, delete
- folder update

### Related issues

closes #363

### Type of change

- [x] New feature (non-breaking change which adds functionality)

### Changes Made

1. added `lastModified` to folder
2. enable filtering by `lastModified` - **not sure if works properly (please test)** 
3. Added integration tests and filters for `lastModified`

### Testing

- [x] Integration Tests

### CODE REVIEW

**Review by genie9 — APPROVED** [review]
:+1:

**Review by teemukataja — APPROVED** [review]
manual testing pending from frontend team

**Comment by genie9** [comment]
`lastModified` index needs to be updated also to https://github.com/CSCfi/metadata-submitter/blob/53c60c7e6242ff3793427ee2f9edc7895bcf70f7/tests/integration/mongo_indexes.py

**Comment by genie9** [comment]
`lastModified` index needs to be updated also to https://github.com/CSCfi/metadata-submitter/blob/53c60c7e6242ff3793427ee2f9edc7895bcf70f7/tests/integration/mongo_indexes.py

**Review by genie9 — CHANGES_REQUESTED** [review]
https://github.com/CSCfi/metadata-submitter/pull/406#issuecomment-1120984804

**Review by genie9 — APPROVED** [review]

**Pull request merged**
